### ISSUE TITLE
macos or macosx

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/quickscript#25]
this is bugging me but I can't work it out

> This is faulty: it should be `macos`

https://github.com/Metaxal/quickscript-extra/pull/9#discussion_r445376039

But the quickscript manual says `macosx`;  [`define-script`](https://docs.racket-lang.org/quickscript/index.html#%28form._%28%28lib._quickscript%2Fmain..rkt%29._define-script%29%29)
![image](https://user-images.githubusercontent.com/108047/85906895-ac1bb400-b807-11ea-983b-db023f21878b.png)

also the error: 

> Error in script file "/Users/spdegabrielle/Library/Preferences/quickscript/user-scripts/open-terminal.rkt":
>  /Users/spdegabrielle/Library/Preferences/quickscript/user-scripts/open-terminal.rkt:8.0: define-script: expected one of these literal symbols: 'unix', '**macosx**', or 'windows'
>   at: macos
>   in: (define-script open-terminal #:label "Open terminal here" #:menu-path ("&Utils") #:os-types (unix macos windows) #:output-to message-box (case (system-type (quote os)) ((unix) (λ (str #:file f) (define dir (path->string (path-only f))) (system (string-a...
>

**Comment by Metaxal** [comment]
Oh, oops you are right! Turns out I was using an old version of quickscript after which I had fixed this typo (but couldn't test and didn't remember), so it was unduly raising an exception.

I reverted the commit (well, I couldn't find out how to revert it on github, so I just fixed it actually).

My apologies! I found it strange that you "didn't see" this compile-time exception in DrRacket before :) There was a good reason why!
