### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/quickscript#3]
this is the error

![screen shot 2017-12-31 at 11 22 26](https://user-images.githubusercontent.com/108047/34461217-e8f76354-ee1c-11e7-9baa-b7f891b794c5.png)
(full text below)

While /Users/spdegabrielle/Library/Preferences/quickscript is created, library.rktd is not present on this system.

I'm investigating and will let you know what I find out.

Stephen
(happy new year!)

--
load: contract violation
  expected: file-exists?
  given: #<path:/Users/spdegabrielle/Library/Preferences/quickscript/library.rktd>
  in: an and/c case of
      the 1st argument of
      (->*
       ()
       ((and/c path-string? file-exists?))
       library?)
  contract from: 
      <pkgs>/quickscript/library.rkt
  blaming: <pkgs>/quickscript/tool.rkt
   (assuming the contract is correct)
  at: <pkgs>/quickscript/library.rkt:79.2
  context...:
   /Applications/Racket v6.11/collects/racket/contract/private/blame.rkt:163:0: raise-blame-error16
   ...ow-val-first.rkt:306:25
   /Users/spdegabrielle/Library/Racket/6.11/pkgs/quickscript/tool.rkt:211:8: reload-scripts-menu
   /Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0: continue-make-object
   /Applications/Racket v6.11/share/pkgs/deinprogramm-signature/deinprogramm/signature/tool.rkt:18:6
   /Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0: continue-make-object
   /Applications/Racket v6.11/share/pkgs/htdp-lib/stepper/xml-tool.rkt:339:8
   /Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0: continue-make-object
   /Applications/Racket v6.11/share/pkgs/htdp-lib/stepper/stepper-tool.rkt:221:2
   /Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0: continue-make-object
   /Applications/Racket v6.11/share/pkgs/htdp-lib/test-engine/test-tool.scm:73:6
   /Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0: continue-make-object
   /Applications/Racket v6.11/share/pkgs/htdp-lib/xml/text-box-tool.rkt:21:5
   /Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0: continue-make-object
   [repeats 1 more time]
   /Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3507:0: do-make-object
   ...

**Comment by Metaxal** [comment]
Ha! That's case of a too strict contract. The file does not need to exist
for the procedure to work.

The contract should be
(->*
[]
[path-string?]
library?)

I'm traveling so can't update it right now.

Happy new year's eve!


On 31 Dec 2017 12:25, "Stephen De Gabrielle" <notifications@github.com>
wrote:

this is the error

[image: screen shot 2017-12-31 at 11 22 26]
<https://user-images.githubusercontent.com/108047/34461217-e8f76354-ee1c-11e7-9baa-b7f891b794c5.png>
(full text below)

While /Users/spdegabrielle/Library/Preferences/quickscript is created,
library.rktd is not present on this system.

I'm investigating and will let you know what I find out.

Stephen
(happy new year!)

--
load: contract violation
expected: file-exists?
given: #path:/Users/spdegabrielle/Library/Preferences/
quickscript/library.rktd
in: an and/c case of
the 1st argument of
(->*
()
((and/c path-string? file-exists?))
library?)
contract from:
/quickscript/library.rkt
blaming: /quickscript/tool.rkt
(assuming the contract is correct)
at: /quickscript/library.rkt:79.2
context...:
/Applications/Racket v6.11/collects/racket/contract/private/blame.rkt:163:0:
raise-blame-error16
...ow-val-first.rkt:306:25
/Users/spdegabrielle/Library/Racket/6.11/pkgs/quickscript/tool.rkt:211:8:
reload-scripts-menu
/Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0:
continue-make-object
/Applications/Racket v6.11/share/pkgs/deinprogramm-signature/deinprogramm/
signature/tool.rkt:18:6
/Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0:
continue-make-object
/Applications/Racket v6.11/share/pkgs/htdp-lib/stepper/xml-tool.rkt:339:8
/Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0:
continue-make-object
/Applications/Racket v6.11/share/pkgs/htdp-lib/
stepper/stepper-tool.rkt:221:2
/Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0:
continue-make-object
/Applications/Racket v6.11/share/pkgs/htdp-lib/
test-engine/test-tool.scm:73:6
/Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0:
continue-make-object
/Applications/Racket v6.11/share/pkgs/htdp-lib/xml/text-box-tool.rkt:21:5
/Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3553:0:
continue-make-object
[repeats 1 more time]
/Applications/Racket v6.11/collects/racket/private/class-internal.rkt:3507:0:
do-make-object
...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Metaxal/quickscript/issues/3>, or mute the thread

**Comment by spdegabrielle** [comment]
Happy new year to you too!

**Comment by Metaxal** [comment]
I'm marking this as closed but feel free to reopen it if it doesn't work for you.
