### ISSUE TITLE
Trouble with "reverse" script

### ISSUE THREAD

**Issue by bennn** [Metaxal/quickscript#39]
I haven't been able to run the first "reverse" script from the docs. So far I've tried 7.6 BC, 7.6 CS, and 7.7 BC.

#### First problem:
the script in the docs expects a string, but gets a list of characters.

#### Second problem:
when I switched from 7.6 BC to 7.6 CS, DrRacket gave this error while loading. Is there a way to avoid it?
```
Error in script file "/Users/ben/Library/Preferences/quickscript/user-scripts/paren-color.rkt":
 read-compiled-linklet: virtual-machine mismatch  expected: "chez-scheme"  found: "racket"  in: /Users/ben/Library/Preferences/quickscript/user-scripts/compiled/paren-color_rkt.zo
```

#### Third, big problem:
when I changed the reverse script to compute `(list->string (reverse selection))` and tried running it on a small `racket/base` program, DrRacket became unresponsive.

I opened the Activity Monitor (I'm on OSX El Capitan), saw DrRacket asking for 7GB of memory, and killed it.

The same high-memory-use happens on all the DrRacket versions I've tried, even when I compile and reload scripts from the menu.

**Comment by Metaxal** [comment]
These are all because the docs are outdated on pkg. Please refer to [these docs](https://www.cs.utah.edu/plt/snapshots/current/doc/quickscript/index.html?q=quickscript#%28part._.Make_your_own_script__.First_simple_example%29) instead.

The reason is a name collision between `reverse` as the name of the script and the reserved racket function.

I'm so sad many people must have tried quickscript, faced the same issue, and just quit :(

**Comment by Metaxal** [comment]
For the second problem, quickscript should have recompiled the script automatically when detecting the compilation mismatch, but apparently it didn't. You can then click on Scripts > Manage scripts... > Compile and it should go away.

Thanks for the reports! Keep me posted.

**Comment by bennn** [comment]
The name collision still sounds like a bug. Do I need to avoid every name provided by `#lang racket`? What if a future release adds a name that overrides one of my scripts?

**Comment by spdegabrielle** [comment]
@bennn 

I wasn't sure so I tested by making a new script that had the same name 'racket-news' as an existing one; 

```racket
#lang racket/base
;;; License: MIT/Apache2.0
(require browser/external
         quickscript)
(script-help-string "Racket Survey.")
(define-script racket-news
  #:label "Racket Survey (browser)"
  #:menu-path ("&News")
  #:help-string "Complete the Racket Survey now"
  (λ (str) 
    (send-url "https://forms.gle/XeHdgv8R7o2VjBbF9")
    #f))
```

```racket 
#lang racket/base

;;; License: MIT/Apache2.0

(require browser/external
         quickscript)

(script-help-string "Racket news and events.")

; Launch https://racket-news.com in browser
(define-script racket-news
  #:label "Racket News (browser)"
  #:menu-path ("&News")
  #:help-string "Opens racket-news.com"
  (λ (str) 
    (send-url "https://racket-news.com")
    #f))
```

Good news ! They didn't trample each other so Laurent @Metaxal is keeping them separate. (but now I want to know how to call other scripts, chain scripts and other madness).

**Comment by Metaxal** [comment]
@bennn Names should not collide between scripts, unless they require one another (scripts are really just modules, and the script's functions are exported just like normal functions).

Yes, you should avoid redefining racket's default exports, _if you intend to use them in the script_. This is exactly the same problem as normal racket. What you wrote (what the docs told you to write) was akin to:
```racket
#lang racket

(define (reverse selection)
  (list->string (reverse (string->list selection))))
```
which, since racket's `reverse` is shadowed, is really just bad code. I don't intend to 'fix' racket's behaviour, so it will remain like this (until/unless racket's behaviour changes).

If a future release exports something with the same name as one of your script's functions, it's all fine because your script will just shadow these exports.

**Comment by Metaxal** [comment]
I'm keeping this issue open for the second problem:

> when I switched from 7.6 BC to 7.6 CS, DrRacket gave this error while loading. Is there a way to avoid it?
> 
> > Error in script file "/Users/ben/Library/Preferences/quickscript/user-scripts/paren-color.rkt":
> >  read-compiled-linklet: virtual-machine mismatch  expected: "chez-scheme"  found: "racket"  in: /Users/ben/Library/Preferences/quickscript/user-scripts/compiled/paren-color_rkt.zo
> >

**Comment by bennn** [comment]
Then again, should a script be able to call itself?

Maybe the script name shouldn't be bound in its body. That's what I was expecting. Though I could have looked at the DrRacket arrows for help, and I also didn't know I could have more than one `define-script` in a file.

**Comment by Metaxal** [comment]
This behaviour allows script to act as functions, and script files to act as modules.
This is used by 'shadow scripts', which are script files that require another script file and call its scripts with the same function names, but redefine the scripts properties (label, menu item, shortcut, etc.)

This allows for installing a third-party script from a package, and either use it as is, or create a shadow script in the user's directory to redefine the properties without touching the script. Hence the package can be updated, this will update the base script but will not override the shadow script.

**Comment by Metaxal** [comment]
I suppose the reason why you expected otherwise is because nowadays in Racket no one writes:
```racket
(define foo
  (lambda (x)
    ...
    (foo (+ x 2)))
```
The script is really just the same thing, with keywords in the middle. The distance between the name and the lambda is larger though, making the visual binding a little less immediate.

**Comment by Metaxal** [comment]
I created a new issue for your second point in the top post, so feel free to close this one if you are satisfied with the answers for the other two points. Also feel free to open a new issue if something else is troubling you. Feedback is always welcome!

**Comment by bennn** [comment]
Two thoughts:

1. Still, should a script be able to call itself? Maybe `let` is better than `letrec`/`define` here. The behaviors you list above are all about having an external name.  ... Then again, why disallow something that might be useful later.

2. Instead, can scripts have contracts? That would have given me a better error at the start, when the reverse script called itself. (Better than a `string->list` contract violation.)

**Comment by Metaxal** [comment]
1. I don't find it a good enough reason to restrict this behaviour, so for now at least I'll leave it as it is.
2. Contracts would be interesting indeed, and I could certainly include a default contract in the template.
I see at least two hindrances though:
* This would make the template bulkier, and would be a significant cognitive barrier to the new user (maybe less so that poor/buggy documentation, but still).
* If you change the signature of the function to request `#:file` or `#:editor` and such, you need to know what the new contract should be. This requires some research for the casual user.

I want quickscripts to be easy and fast to write: There's suddenly a small task you want to automate, just hit Script > New.

Maybe I should add a section in the docs about "Making your script robust", and say that contracts can be used?

**Comment by bennn** [comment]
I was thinking `define-script` should make the contract.

The user doesn't do any work; they can just trust the docs about what their function will get.

**Comment by Metaxal** [comment]
Maybe that's possible indeed, I'll add an issue to keep this in mind.
