### ISSUE TITLE
Disabled Scripts with syntax errors cause popup on DrRacket startup

### ISSUE THREAD

**Issue by rfindler** [Metaxal/quickscript#48]
One of my scripts, bars.rkt, has a free identifier in it. It is disabled via the Manage Scripts | Disable Scripts... menu:

<img width="912" alt="Screen Shot 2020-08-09 at 10 34 32 AM" src="https://user-images.githubusercontent.com/399024/89736005-fe1d3f80-da2b-11ea-8ec7-f27d3fb7b585.png">

When I start up DrRacket, however, I see this message:

<img width="608" alt="Screen Shot 2020-08-09 at 10 35 55 AM" src="https://user-images.githubusercontent.com/399024/89736024-286efd00-da2c-11ea-9a7b-f8fb0a68c689.png">

Probably it should be ignored, since it is disabled?

**Comment by rfindler** [comment]
This message actually appears each time I open a new DrRacket window (but not new tab).

**Comment by Metaxal** [comment]
Thanks for the report! Indeed that's the current behaviour and it needs to change.

The reason behind this is 'shadow scripts'. Since the shadowed script is disabled, it still needs to be compiled if the shadowing script is compiled. I thought that `compile-zos` does not recompile dependencies, so I chose to recompile everything, but that's not ideal.

Ideally, the dependencies of scripts should be recompiled too (the shadowed script is a dependency of the shadowing script), but I'm not sure what's the right way to do it.

So my question is: What's the correct way to recompile dependencies?

**Comment by Metaxal** [comment]
Matthew just confirmed that `compile-zos` doesn't compile dependencies, but `compile-directory-zos` does, so I'll try to switch to the latter.

**Comment by Metaxal** [comment]
The last commit should resolve your problem. Can you confirm it works as expected?
